version: '2'
services: 
  kaart:
    build:
      context: ./docker
    ports:
      - "8088:80"
    volumes:
      - ./:/htdocs
    environment:
      TZ: "Europe/Amsterdam"
      KAART_GEO_DB: ${KAART_GEO_DB}
      KAART_NLGIS_DB: ${KAART_NLGIS_DB}
      KAART_GEO_DB_HOST: ${KAART_GEO_DB_HOST}
      KAART_GEO_DB_USER: ${KAART_GEO_DB_USER}
      KAART_GEO_DB_PASSWORD: ${KAART_GEO_DB_PASSWORD}
      REST_ALLOWED_CLIENTS: ${REST_ALLOWED_CLIENTS}
